#!/bin/bash

# Script pour désactiver temporairement les symboles "TOO_RECENT"
# Usage: ./scripts/switch_off_too_recent_symbols.sh [duration] [dry-run]

# Configuration par défaut
DURATION=${1:-"38640m"}  # 38640 minutes par défaut (environ 26 jours)
DRY_RUN=${2:-""}         # Mode dry-run optionnel

# Liste des symboles TOO_RECENT
SYMBOLS="1000000MOGUSDT,1000BONKUSDT,1000CHEEMSUSDT,1000LUNCUSDT,1000PEPEUSDT,1000RATSUSDT,1000SATSUSDT,1000SHIBUSDT,1000WHYUSDT,1INCHUSDT,1MBABYDOGEUSDT,AAPLXUSDT,AAVEUSDT,ACEUSDT,ACHUSDT,ACTUSDT,ADAUSDT,AEROUSDT,AGLDUSDT,AGTUSDT,AI16ZUSDT,AINUSDT,AIOTUSDT,AIOUSDT,AIUSDT,AIXBTUSDT,ALCHUSDT,ALGOUSDT,ALICEUSDT,ALPINEUSDT,ALTUSDT,ANKRUSDT,APEUSDT,API3USDT,APTUSDT,ARBUSDT,ARCUSDT,ARKMUSDT,ARUSDT,ASPUSDT,ASRUSDT,ATHUSDT,ATOMUSDT,AUCTIONUSDT,AUSDT,AVAAIUSDT,AVAUSDT,AVAXUSDT,AXSUSDT,BABYUSDT,BANANAS31USDT,BANANAUSDT,BANDUSDT,BANKUSDT,BANUSDT,BASUSDT,BATUSDT,BBUSDT,BCHUSDT,BERAUSDT,BIDUSDT,BIOUSDT,BLASTUSDT,BLURUSDT,BMTUSDT,BNBUSDT,BOMEUSDT,BRETTUSDT,BROCCOLIF3BUSDT,BROCCOLIUSDT,BTCUSDT,BTRUSDT,BULLAUSDT,BUSDT,C98USDT,CAKEUSDT,CAMPUSDT,CARVUSDT,CATUSDT,CELOUSDT,CETUSUSDT,CFXUSDT,CHILLGUYUSDT,CHZUSDT,CKBUSDT,COINXUSDT,COMPUSDT,COOKIEUSDT,COREUSDT,COWUSDT,CRCLXUSDT,CROSSUSDT,CROUSDT,CRVUSDT,CTKUSDT,CTSIUSDT,CUSDT,CVXUSDT,CYBERUSDT,DAMUSDT,DEEPUSDT,DMCUSDT,DOGEUSDT,DOGSUSDT,DOGUSDT,DOLOUSDT,DOTUSDT,DRIFTUSDT,DYDXUSDT,EGLDUSDT,EIGENUSDT,ENAUSDT,ENJUSDT,ENSUSDT,EPICUSDT,ERAUSDT,ESPORTSUSDT,ESUSDT,ETCUSDT,ETHFIUSDT,ETHUSDT,ETHWUSDT,FARTCOINUSDT,FETUSDT,FILUSDT,FISUSDT,FLOKIUSDT,FLOWUSDT,FORTHUSDT,FRAGUSDT,FUNUSDT,FXSUSDT,GALAUSDT,GASUSDT,GLMUSDT,GMTUSDT,GMXUSDT,GOATUSDT,GRASSUSDT,GRIFFAINUSDT,GRTUSDT,HAEDALUSDT,HBARUSDT,HEMIUSDT,HFTUSDT,HIGHUSDT,HIPPOUSDT,HMSTRUSDT,HOOKUSDT,HUMAUSDT,HUSDT,HYPERUSDT,HYPEUSDT,ICNTUSDT,ICPUSDT,ILVUSDT,IMXUSDT,INITUSDT,INJUSDT,INUSDT,IOSTUSDT,IOTAUSDT,IOTXUSDT,IOUSDT,IPUSDT,JASMYUSDT,JELLYJELLYUSDT,JOEUSDT,JTOUSDT,JUPUSDT,KAIUSDT,KAITOUSDT,KASUSDT,KAVAUSDT,KDAUSDT,KERNELUSDT,LAUNCHCOINUSDT,LAUSDT,LAYERUSDT,LDOUSDT,LINKUSDT,LISTAUSDT,LPTUSDT,LRCUSDT,LTCUSDT,MAGICUSDT,MANAUSDT,MANTAUSDT,MASKUSDT,MAVIAUSDT,MAVUSDT,MELANIAUSDT,MEMEUSDT,MEWUSDT,MINAUSDT,MITOUSDT,MOCAUSDT,MOODENGUSDT,MORPHOUSDT,MOVEUSDT,MOVRUSDT,MUBARAKUSDT,MUSDT,MYROUSDT,MYXUSDT,NAORISUSDT,NEARUSDT,NEIROUSDT,NEOUSDT,NOTUSDT,NVDAXUSDT,OGNUSDT,OGUSDT,OMUSDT,ONDOUSDT,ONEUSDT,ONTUSDT,OPUSDT,ORCAUSDT,ORDIUSDT,PAXGUSDT,PENDLEUSDT,PENGUUSDT,PEOPLEUSDT,PIPPINUSDT,PIUSDT,PIXELUSDT,PLAYUSDT,PLUMEUSDT,POLUSDT,POPCATUSDT,PORT3USDT,PORTALUSDT,PROMPTUSDT,PROMUSDT,PROVEUSDT,PUMPUSDT,PYTHUSDT,QNTUSDT,QTUMUSDT,RAREUSDT,RAYUSDT,RDNTUSDT,RENDERUSDT,REZUSDT,RONINUSDT,ROSEUSDT,RPLUSDT,RSRUSDT,RUNEUSDT,RVNUSDT,SAFEUSDT,SAHARAUSDT,SANDUSDT,SANTOSUSDT,SAPIENUSDT,SEIUSDT,SFPUSDT,SHELLUSDT,SKATEUSDT,SLERFUSDT,SLPUSDT,SNXUSDT,SOLUSDT,SOLVUSDT,SONICUSDT,SOONUSDT,SPELLUSDT,SPKUSDT,SPXUSDT,SQDUSDT,STORJUSDT,STRKUSDT,STXUSDT,SUIUSDT,SUNUSDT,SUPERUSDT,SUSDT,SUSHIUSDT,SWARMSUSDT,SWELLUSDT,SXPUSDT,SYNUSDT,SYRUPUSDT,TACUSDT,TANSSIUSDT,TAOUSDT,TAUSDT,THETAUSDT,THEUSDT,TIAUSDT,TNSRUSDT,TONUSDT,TOWNSUSDT,TRBUSDT,TREEUSDT,TRUMPUSDT,TRXUSDT,TSTUSDT,TWTUSDT,UNIUSDT,USDCUSDT,USELESSUSDT,USTCUSDT,USUALUSDT,VANAUSDT,VANRYUSDT,VELODROMEUSDT,VELVETUSDT,VETUSDT,VICUSDT,VINEUSDT,VIRTUALUSDT,WALUSDT,WCTUSDT,WIFUSDT,WLDUSDT,WOOUSDT,WUSDT,XAIUSDT,XAUTUSDT,XCNUSDT,XLMUSDT,XMRUSDT,XNYUSDT,XRPUSDT,XTZUSDT,YALAUSDT,YFIUSDT,YGGUSDT,ZBCNUSDT,ZENUSDT,ZEREBROUSDT,ZETAUSDT,ZILUSDT,ZKJUSDT,ZKUSDT,ZORAUSDT,ZRCUSDT,ZROUSDT,ZRXUSDT"

echo "=== Désactivation temporaire des symboles TOO_RECENT ==="
echo "Durée: $DURATION"
echo "Mode dry-run: ${DRY_RUN:-NON}"
echo ""

# Compter le nombre de symboles
SYMBOL_COUNT=$(echo "$SYMBOLS" | tr ',' '\n' | wc -l)
echo "Nombre de symboles à traiter: $SYMBOL_COUNT"
echo ""

# Construire la commande
CMD="php bin/console mtf:switch-off --symbols=\"$SYMBOLS\" --duration=\"$DURATION\" --reason=\"TOO_RECENT\""

if [ "$DRY_RUN" = "dry-run" ]; then
    CMD="$CMD --dry-run"
fi

echo "Commande à exécuter:"
echo "$CMD"
echo ""

# Demander confirmation
read -p "Voulez-vous continuer? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Opération annulée."
    exit 0
fi

echo ""
echo "Exécution en cours..."
echo ""

# Exécuter la commande
eval $CMD

echo ""
echo "=== Opération terminée ==="
