# Liste d'événements macro-économiques bloquants pour la stratégie High Conviction.
# Ajoute ou modifie les entrées en fonction de ton calendrier.
# Chaque bloc accepte :
#   at (ISO8601, UTC par défaut),
#   label,
#   window_minutes (durée pendant laquelle on bloque avant/après l'événement),
#   symbols (facultatif, sinon l'événement s'applique à tous les symboles),
#   impact (optionnel, à but informatif).
events:
  # Exemple : décision FED
  - at: '2025-01-10T19:00:00Z'
    label: 'FOMC Rate Decision'
    window_minutes: 120
    symbols: ['*']
    impact: high
