# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    pythonApiBaseUrl: '%env(resolve:PYTHON_API_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Controller\IndicatorController:
        arguments:
            $pythonApiBaseUrl: '%pythonApiBaseUrl%'
    App\Command\DispatchContractTaskCommand:
        arguments:
            $signalApiUrl: '%env(SIGNAL_API_URL)%'


    App\Service\Exchange\Bitmart\BitmartFetcher:
        arguments:
            $httpClient: '@http_client'
        tags: [ 'mon.exchange.fetcher' ]

    App\Service\ExchangeFetcherInterface: '@App\Service\Exchange\Bitmart\BitmartFetcher'
    Symfony\Component\Clock\NativeClock: ~
    Symfony\Component\Clock\ClockInterface: '@Symfony\Component\Clock\NativeClock'
    App\State\BitmartKlineProvider:
        tags: [ 'api_platform.state_provider' ]

    clock.test:
        class: Symfony\Component\Clock\MockClock
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
