server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # =====================
  # --- Symfony Logs ---
  # =====================
  - job_name: symfony_trading_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: symfony
          app: trading-app
          env: ${APP_ENV:-dev}
          __path__: /var/log/symfony/*.log
    
    # Pipeline de transformation pour parser les logs structurés
    pipeline_stages:
      # Parse le format de log personnalisé (plus flexible)
      - regex:
          expression: '^\[?(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\]?\[?(?P<channel>\w+)\.(?P<level>\w+)\]?: (?P<message>.*)$'
      
      # Parse les métadonnées de trading
      - regex:
          expression: '\[(?P<symbol>\w+)\]\[(?P<timeframe>\w+)\]\[(?P<side>\w+)\] (?P<content>.*)$'
          source: message
      
      # Ajouter des labels pour le filtrage
      - labels:
          channel:
          level:
          symbol:
          timeframe:
          side:
      
      # Timestamp parsing
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
          action_on_failure: fudge
          fudge: 1s
      
      # Output final
      - output:
          source: content