api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        html: ['text/html']
        json: ['application/json']
        jsonld: ['application/ld+json']
    swagger:
        versions: [3]
        api_keys: []
        persist_authorization: true
        swagger_ui_extra_configuration:
            docExpansion: none

