# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session: true
    http_client:
        scoped_clients:
            http_client.bitmart_futures_v2:
                base_uri: 'https://api-cloud-v2.bitmart.com'
                headers:
                    Accept: 'application/json'
                    User-Agent: 'YourApp/1.0 (+https://example.com)'
                timeout: 10
                retry_failed:
                    enabled: false

            # Client privé signé: même base_uri que futures_v2, mais utilisé avec headers dynamiques
            http_client.bitmart_futures_v2_private:
                base_uri: 'https://api-cloud-v2.bitmart.com'
                headers:
                    Accept: 'application/json'
                    User-Agent: 'YourApp/1.0 (+https://example.com)'
                timeout: 10
                retry_failed:
                    enabled: false

            http_client.bitmart_system:
                base_uri: 'https://api-cloud.bitmart.com'   # ← domaine “classique” (Spot/System)
                headers:
                    Accept: 'application/json'
                    User-Agent: 'YourApp/1.0 (+https://example.com)'
                timeout: 10
                retry_failed:
                    enabled: false

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
