# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session: true
    http_client:
        scoped_clients:
            python.client:
                base_uri: '%env(INDICATOR_BASE)%'
                timeout: 30

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
