version: 1.1
strategy: high_conviction
description: "Contexte rare et puissant autorisant un levier élevé (jusqu'à 50x)."

conditions:
    multi_timeframe_alignment:
        required: true
    signals: ["context_4h","context_1h","exec_15m"]
    rule: "all_equal_non_neutral"   # tous LONG ou tous SHORT, aucun NEUTRE

    trend_strength:
        required: true
        indicator: "ADX"
    params: { length: 14, buffer: 1.0 }
        timeframe: ["1h","15m"]
        rule: "min_value"
        threshold: 25

    breakout_with_volume:
        required: true
    indicators: ["Donchian20","OBV","VWAP","Volume"]
        rule: "breakout_confirmed"
    params:
      vol_multiplier: 1.5        # Volume >= 1.5x moyenne 20
      require_vwap_alignment: true

    volatility_expansion:
        required: true
    indicators: ["ATR14","Bollinger20_2","Choppiness14"]
        rule: "expansion_after_contraction"
    params:
      chop_max: 38
      bb_width_percentile: 5      # squeeze si largeur bandes <= p5 252j
      atr_bars_up: 3

    no_macro_event:
        required: true
        source: "calendar_feed"
    rule: "no_event_window"
    params:
      blackout_minutes_before: 60
      blackout_minutes_after: 30
      events: ["FOMC","CPI","NFP","RateDecision"]

    micro_tf_confirmation:
        required: true
    signals: ["exec_5m","micro_1m"]
        rule: "valid_retest"
    params: { max_wick_ratio: 0.25, max_retests: 1 }

    rr_guard:
        required: true
        indicator: "RR"
        threshold: 5.0
    params: { tp_method: "tech_target", sl_method: "atr_or_structure" }

    liquidation_guard:
        required: true
        indicator: "liquidation_guard"
    threshold: 3.0                 # liq ≥ 3× stop
    params: { exchange: "BitMart", mode: "isolated" }

risk_management:
  base_risk_pct: 2.0
  max_risk_pct: 2.0
  leverage_mode: high
  leverage_cap: 50
  dynamic_leverage:
    enabled: true
    formula: "min(leverage_cap, max(plancher, k / stop_pct))"
    params: { k: 10, plancher: 3, plafond: 50 }
  budget_usdt: 100
  stop_min_pct: 0.25
  time_stop_minutes: 180
  position_addition: "mfe_only"    # add à +1R et +2R après re-validation guards
  cooldown_minutes: 15
  sl_tp:
    type: "OCO"
    trailing:
      mode: "ATR"
      atr_length: 14
      multiplier: 2.5

execution:
  prefer: "maker"
  fallback: "taker"
  slip_guard_bps: 8
  quantization: { tick: "exchange", step: "exchange" }

flags:
    high_conviction: true
