monolog:
    channels: ['validation', 'signals', 'indicators', 'deprecation', 'positions']  # <- remplacez 'position' par 'positions'

    handlers:
        # === Validation ===
        validation_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/validation.log'
            level: info
            max_files: 14
            channels: ['validation']
            formatter: App\Logging\CustomLineFormatter

        validation_buffered:
            type: fingers_crossed
            action_level: warning
            handler: validation_rotating
            channels: ['validation']

        # === Signals ===
        signals_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/signals.log'
            level: info
            max_files: 14
            channels: ['signals']
            formatter: App\Logging\CustomLineFormatter

        # === Positions ===
        positions_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/positions.log'
            level: info
            max_files: 14
            channels: ['positions']
            formatter: App\Logging\CustomLineFormatter

        # === Indicators ===
        indicators_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/indicators.log'
            level: info
            max_files: 14
            channels: ['indicators']
            formatter: App\Logging\CustomLineFormatter

        main:
            type: stream
            path: "php://stderr"
            level: info

        console:
            type: console
when@dev:
    monolog:
        handlers:
            # fichiers verbeux en dev
            validation_rotating:
                level: debug
            signals_rotating:
                level: debug
            indicators_rotating:
                level: debug

            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
when@prod:
    monolog:
        handlers:
            # on met un buffer sur validation pour n’écrire qu’en cas de warning+
            validation_buffered:
                action_level: warning
                buffer_size: 200

            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: App\Logging\CustomLineFormatter

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: App\Logging\CustomLineFormatter
