monolog:
    channels: ['validation', 'signals', 'indicators', 'deprecation', 'positions', 'highconviction']  # ajout du canal

    handlers:
        # === Validation ===
        validation_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/validation.log'
            level: info
            max_files: 14
            channels: ['validation']
            formatter: App\Logging\CustomLineFormatter

        validation_buffered:
            type: fingers_crossed
            action_level: warning
            handler: validation_rotating
            channels: ['validation']

        # === Signals ===
        signals_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/signals.log'
            level: info
            max_files: 14
            channels: ['signals']
            formatter: App\Logging\CustomLineFormatter

        # === Positions ===
        positions_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/positions.log'
            level: info
            max_files: 14
            channels: ['positions']
            formatter: App\Logging\CustomLineFormatter

        # === Indicators ===
        indicators_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/indicators.log'
            level: info
            max_files: 14
            channels: ['indicators']
            formatter: App\Logging\CustomLineFormatter

        # === HighConviction ===
        highconviction_rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/highconviction.log'
            level: info
            max_files: 14
            channels: ['highconviction']
            formatter: App\Logging\CustomLineFormatter

        main:
            type: stream
            path: "php://stderr"
            level: info

        console:
            type: console

when@dev:
    monolog:
        handlers:
            validation_rotating:
                level: debug
            signals_rotating:
                level: debug
            indicators_rotating:
                level: debug
            highconviction_rotating:
                level: debug   # en dev, log + verbeux pour HC

            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            # === Global severity (>= notice) sur tous les channels ===
            global_severity_rotating:
                type: rotating_file
                path: '%kernel.logs_dir%/global-severity.log'
                level: error          # exclut debug & info, garde notice et plus
                max_files: 30
                formatter: App\Logging\CustomLineFormatter
                # pas de "channels:" -> s’applique à tous les channels

when@prod:
    monolog:
        handlers:
            validation_buffered:
                action_level: warning
                buffer_size: 200

            highconviction_rotating:   # en prod, fichier dédié info+
                type: rotating_file
                path: '%kernel.logs_dir%/highconviction.log'
                level: info
                max_files: 30
                channels: ['highconviction']
                formatter: App\Logging\CustomLineFormatter

            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50

            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: App\Logging\CustomLineFormatter

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: App\Logging\CustomLineFormatter
