# config/packages/trading.yaml
parameters:
    app.trading:
        validation_order:
            - '4h'
            - '1h'
            - '15m'
            - '5m'
            - '1m'

        risk:
            risk_per_trade_pct: 1
            sl_atr_mult: 1.5
            tp_rr: 2
            fees_bps: 5

        timeframes:
            '4h':
                indicators:
                    ema50:    { type: ema, period: 50,  source: close }
                    ema200:   { type: ema, period: 200, source: close }
                    adx14:    { type: adx, period: 14 }
                    ichimoku: { type: ichimoku, tenkan: 9, kijun: 26, senkou_b: 52 }

                long:
                    # Identifiants des critères pour le scoring
                    criteria:
                        ema_trend:
                            # ema50 > ema200
                            above: { left: ema50, right: ema200 }
                        trend_strength:
                            # ADX > 20
                            above: { left: adx14, value: 20 }
                        ichimoku_filter:
                            # Kijun support / prix au-dessus du nuage (simplifié)
                            any:
                                - above: { left: close, right: ichimoku.kijun }
                                - above: { left: close, right: ichimoku.senkou_span_a }

                    # Règle finale (doit être vraie pour considérer le signal 4H)
                    rule:
                        all:
                            - ref: ema_trend
                            - ref: trend_strength
                            - ref: ichimoku_filter

                    score:
                        weights:
                            ema_trend: 0.5
                            trend_strength: 0.3
                            ichimoku_filter: 0.2
                        pass_threshold: 0.55

                short:
                    criteria:
                        ema_trend:
                            above: { left: ema200, right: ema50 }   # ema200 > ema50
                        trend_strength:
                            above: { left: adx14, value: 20 }
                        ichimoku_filter:
                            any:
                                - above: { left: ichimoku.kijun,       right: close }
                                - above: { left: ichimoku.senkou_span_a, right: close }

                    rule:
                        all: [ {ref: ema_trend}, {ref: trend_strength}, {ref: ichimoku_filter} ]

                    score:
                        weights: { ema_trend: 0.5, trend_strength: 0.3, ichimoku_filter: 0.2 }
                        pass_threshold: 0.55
            '1h':
                indicators:
                    ema50: { type: ema, period: 50,  source: close }
                    ema200: { type: ema, period: 200, source: close }
                    adx14: { type: adx, period: 14 }
                    ichimoku: { type: ichimoku, tenkan: 9, kijun: 26, senkou_b: 52 }
                    rsi14: { type: rsi, period: 14, source: close }
                    macd: { type: macd, fast: 12, slow: 26, signal: 9, source: close }
                    bb20: { type: bollinger, period: 20, stdev: 2, source: close, output: [ upper, lower, middle, width ] }

                long:
                    criteria:
                        # Filtres de régime (en “astuce” si pas d’opérateur below)
                        trend_regime: { above: { left: adx14, value: 25 } }     # ADX >= 25
                        range_regime: { above: { left: 20, right: adx14 } }     # ADX <= 20

                        ema_trend: { above: { left: ema50, right: ema200 } }
                        macd_trend: { above: { left: macd.macd, right: macd.signal } }
                        ichi_filter:
                            any:
                                - { above: { left: close, right: ichimoku.kijun } }
                                - { above: { left: close, right: ichimoku.senkou_span_a } }

                        rsi_momentum: { above: { left: rsi14, value: 50 } }     # RSI > 50
                        bb_expansion: { slope_up: { left: bb20.width, lookback: 3 } }

                        # Deux chemins “validants”
                        trend_long:
                            all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: macd_trend } ]
                        range_long:
                            all: [ { ref: range_regime }, { ref: rsi_momentum }, { ref: bb_expansion } ]

                    rule:
                        any: [ { ref: trend_long }, { ref: range_long } ]

                    score:
                        weights: { ema_trend: 0.35, macd_trend: 0.25, ichi_filter: 0.15, rsi_momentum: 0.15, bb_expansion: 0.10 }
                        pass_threshold: 0.55

                short:
                    criteria:
                        trend_regime: { above: { left: adx14, value: 25 } }
                        range_regime: { above: { left: 20, right: adx14 } }

                        ema_trend: { above: { left: ema200, right: ema50 } }
                        macd_trend: { above: { left: macd.signal, right: macd.macd } }
                        ichi_filter:
                            any:
                                - { above: { left: ichimoku.kijun,       right: close } }
                                - { above: { left: ichimoku.senkou_span_a, right: close } }

                        rsi_momentum: { above: { left: 50, right: rsi14 } }     # RSI < 50
                        bb_expansion: { slope_up: { left: bb20.width, lookback: 3 } }

                        trend_short:
                            all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: macd_trend } ]
                        range_short:
                            all: [ { ref: range_regime }, { ref: rsi_momentum }, { ref: bb_expansion } ]

                    rule:
                        any: [ { ref: trend_short }, { ref: range_short } ]

                    score:
                        weights: { ema_trend: 0.35, macd_trend: 0.25, ichi_filter: 0.15, rsi_momentum: 0.15, bb_expansion: 0.10 }
                        pass_threshold: 0.55
            '15m':
                guards:
                    min_bars: 220

                indicators:
                    ema_fast: { type: ema, period: 50,  source: close }   # fallback lu par le service
                    ema_slow: { type: ema, period: 200, source: close }
                    adx14: { type: adx, period: 14 }
                    ichimoku: { type: ichimoku, tenkan: 9, kijun: 26, senkou_b: 52 }
                    rsi14: { type: rsi, period: 14,  source: close }
                    macd: { type: macd, fast: 12, slow: 26, signal: 9, source: close }
                    bb20: { type: bollinger, period: 20, stdev: 2, source: close, output: [ upper, lower, middle, width ] }

                regime:
                    trend_min_adx: 23     # tendance >= 23 (15m plus sensible que 1h)
                    range_max_adx: 18     # range <= 18
                    bb_lookback: 3      # pente(width) sur N barres

                long:
                    criteria:
                        trend_regime: { above: { left: adx14, value: 23 } }
                        range_regime: { above: { left: 18, right: adx14 } }     # ADX <= 18

                        ema_trend: { above: { left: ema_fast, right: ema_slow } }
                        macd_cross_up: { cross_up: { left: macd.macd, right: macd.signal } }
                        rsi_cross_up: { cross_up: { left: rsi14, value: 50 } }
                        kijun_break_up:{ cross_up: { left: close, right: ichimoku.kijun } }
                        ichi_price_above:
                            any:
                                - { above: { left: close, right: ichimoku.kijun } }
                                - { above: { left: close, right: ichimoku.senkou_span_a } }

                        rsi_momentum_up: { above: { left: rsi14, value: 50 } }
                        bb_expansion: { slope_up: { left: bb20.width, lookback: 3 } }

                        trigger_any:
                            any: [ { ref: macd_cross_up }, { ref: rsi_cross_up }, { ref: kijun_break_up }, { ref: ichi_price_above } ]

                        trend_long:
                            all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: trigger_any } ]

                        range_long:
                            all: [ { ref: range_regime }, { ref: rsi_momentum_up }, { ref: bb_expansion } ]

                    rule:
                        any: [ { ref: trend_long }, { ref: range_long } ]

                    score:
                        weights:
                            ema_trend: 0.25
                            macd_cross_up: 0.25
                            rsi_cross_up: 0.15
                            kijun_break_up: 0.15
                            ichi_price_above: 0.05
                            rsi_momentum_up: 0.10
                            bb_expansion: 0.05
                        pass_threshold: 0.55

                short:
                    criteria:
                        trend_regime: { above: { left: adx14, value: 23 } }
                        range_regime: { above: { left: 18, right: adx14 } }

                        ema_trend: { above: { left: ema_slow, right: ema_fast } }
                        macd_cross_down: { cross_down: { left: macd.macd, right: macd.signal } }
                        rsi_cross_down: { cross_down: { left: rsi14, value: 50 } }
                        kijun_break_down: { cross_down: { left: close, right: ichimoku.kijun } }
                        ichi_price_below:
                            any:
                                - { above: { left: ichimoku.kijun,        right: close } }
                                - { above: { left: ichimoku.senkou_span_a, right: close } }

                        rsi_momentum_down: { above: { left: 50, right: rsi14 } }
                        bb_expansion: { slope_up: { left: bb20.width, lookback: 3 } }

                        trigger_any:
                            any: [ { ref: macd_cross_down }, { ref: rsi_cross_down }, { ref: kijun_break_down }, { ref: ichi_price_below } ]

                        trend_short:
                            all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: trigger_any } ]

                        range_short:
                            all: [ { ref: range_regime }, { ref: rsi_momentum_down }, { ref: bb_expansion } ]

                    rule:
                        any: [ { ref: trend_short }, { ref: range_short } ]

                    score:
                        weights:
                            ema_trend: 0.25
                            macd_cross_down: 0.25
                            rsi_cross_down: 0.15
                            kijun_break_down: 0.15
                            ichi_price_below: 0.05
                            rsi_momentum_down: 0.10
                            bb_expansion: 0.05
                        pass_threshold: 0.55
            '5m':
                macd_cross_up: { cross_up: { left: macd.macd, right: macd.signal } }
                rsi_cross_up: { cross_up: { left: rsi14, value: 50 } }
                kijun_break_up: { cross_up: { left: close, right: ichimoku.kijun } }
                ichi_price_above:
                any:
                    - { above: { left: close, right: ichimoku.kijun } }
                    - { above: { left: close, right: ichimoku.senkou_span_a } }


                rsi_momentum_up: { above: { left: rsi14, value: 50 } }
                bb_expansion: { slope_up: { left: bb20.width, lookback: 2 } }


                trigger_any:
                any: [ { ref: macd_cross_up }, { ref: rsi_cross_up }, { ref: kijun_break_up }, { ref: ichi_price_above } ]


                trend_long:
                all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: trigger_any } ]


                range_long:
                all: [ { ref: range_regime }, { ref: rsi_momentum_up }, { ref: bb_expansion } ]


                rule:
                any: [ { ref: trend_long }, { ref: range_long } ]


                score:
                weights:
                ema_trend: 0.25
                macd_cross_up: 0.25
                rsi_cross_up: 0.15
                kijun_break_up: 0.15
                ichi_price_above: 0.05
                rsi_momentum_up: 0.10
                bb_expansion: 0.05
                pass_threshold: 0.55


                short:
                criteria:
                trend_regime: { above: { left: adx14, value: 21 } }
                range_regime: { above: { left: 16, right: adx14 } }


                ema_trend: { above: { left: ema_slow, right: ema_fast } }
                macd_cross_down: { cross_down: { left: macd.macd, right: macd.signal } }
                rsi_cross_down: { cross_down: { left: rsi14, value: 50 } }
                kijun_break_down: { cross_down: { left: close, right: ichimoku.kijun } }
                ichi_price_below:
                any:
                    - { above: { left: ichimoku.kijun, right: close } }
                    - { above: { left: ichimoku.senkou_span_a, right: close } }


                rsi_momentum_down: { above: { left: 50, right: rsi14 } }
                bb_expansion: { slope_up: { left: bb20.width, lookback: 2 } }


                trigger_any:
                any: [ { ref: macd_cross_down }, { ref: rsi_cross_down }, { ref: kijun_break_down }, { ref: ichi_price_below } ]


                trend_short:
                all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: trigger_any } ]


                range_short:
                all: [ { ref: range_regime }, { ref: rsi_momentum_down }, { ref: bb_expansion } ]


                rule:
                any: [ { ref: trend_short }, { ref: range_short } ]


                score:
                weights:
                ema_trend: 0.25
                macd_cross_down: 0.25
                rsi_cross_down: 0.15
                kijun_break_down: 0.15
                ichi_price_below: 0.05
                rsi_momentum_down: 0.10
                bb_expansion: 0.05
                pass_threshold: 0.55
            '1m':
                macd_cross_up: { cross_up: { left: macd.macd, right: macd.signal } }
                rsi_cross_up: { cross_up: { left: rsi14, value: 50 } }
                kijun_break_up: { cross_up: { left: close, right: ichimoku.kijun } }
                ichi_price_above:
                any:
                    - { above: { left: close, right: ichimoku.kijun } }
                    - { above: { left: close, right: ichimoku.senkou_span_a } }


                rsi_momentum_up: { above: { left: rsi14, value: 50 } }
                bb_expansion: { slope_up: { left: bb20.width, lookback: 1 } }


                trigger_any:
                any: [ { ref: macd_cross_up }, { ref: rsi_cross_up }, { ref: kijun_break_up }, { ref: ichi_price_above } ]


                trend_long:
                all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: trigger_any } ]


                range_long:
                all: [ { ref: range_regime }, { ref: rsi_momentum_up }, { ref: bb_expansion } ]


                rule:
                any: [ { ref: trend_long }, { ref: range_long } ]


                score:
                weights:
                ema_trend: 0.25
                macd_cross_up: 0.25
                rsi_cross_up: 0.15
                kijun_break_up: 0.15
                ichi_price_above: 0.05
                rsi_momentum_up: 0.10
                bb_expansion: 0.05
                pass_threshold: 0.55


                short:
                criteria:
                trend_regime: { above: { left: adx14, value: 19 } }
                range_regime: { above: { left: 15, right: adx14 } }


                ema_trend: { above: { left: ema_slow, right: ema_fast } }
                macd_cross_down: { cross_down: { left: macd.macd, right: macd.signal } }
                rsi_cross_down: { cross_down: { left: rsi14, value: 50 } }
                kijun_break_down: { cross_down: { left: close, right: ichimoku.kijun } }
                ichi_price_below:
                any:
                    - { above: { left: ichimoku.kijun, right: close } }
                    - { above: { left: ichimoku.senkou_span_a, right: close } }


                rsi_momentum_down: { above: { left: 50, right: rsi14 } }
                bb_expansion: { slope_up: { left: bb20.width, lookback: 1 } }


                trigger_any:
                any: [ { ref: macd_cross_down }, { ref: rsi_cross_down }, { ref: kijun_break_down }, { ref: ichi_price_below } ]


                trend_short:
                all: [ { ref: trend_regime }, { ref: ema_trend }, { ref: trigger_any } ]


                range_short:
                all: [ { ref: range_regime }, { ref: rsi_momentum_down }, { ref: bb_expansion } ]


                rule:
                any: [ { ref: trend_short }, { ref: range_short } ]


                score:
                weights:
                ema_trend: 0.25
                macd_cross_down: 0.25
                rsi_cross_down: 0.15
                kijun_break_down: 0.15
                ichi_price_below: 0.05
                rsi_momentum_down: 0.10
                bb_expansion: 0.05
                pass_threshold: 0.55
