indicators:
  long:
    rsi:
      enabled: true
      score: 1.5
      timeframes: [1m, 5m, 15m, 1h, 4h]
      periods: [6, 14]
      condition: "RSI > 78 (6) OR RSI > 70 (14)"
    ema:
      enabled: true
      score: 1.5
      timeframes: [1m, 5m, 15m, 1h, 4h]
      cross: "EMA9 > EMA21"
      price_vs_ema200: true
    macd:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h, 4h]
      condition: "MACD > Signal AND divergence positive"
    bollinger:
      enabled: true
      score: 1.0
      timeframes: [5m, 15m, 4h]
      condition: "Rebond sur bande inférieure"
    stochastic_rsi:
      enabled: true
      score: 1.2
      timeframes: [1m, 5m]
      condition: "StochRSI < 0.2 + croisement haussier"
    vwap:
      enabled: true
      score: 1.2
      timeframes: [1m, 5m, 15m]
      condition: "Prix > VWAP + volume acheteur"
    volume:
      enabled: true
      score: 1.3
      timeframes: [1m, 5m, 15m, 1h]
      condition: "Volume acheteur anormal sur cassure résistance"
    candle:
      enabled: true
      score: 1.0
      timeframes: [1m, 5m, 15m, 1h]
      pattern: "Rejet bas (bougie verte avec mèche basse dominante)"
    supertrend:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h, 4h]
      condition: "Prix > Supertrend"
    adx:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h, 4h]
      condition: "+DI > -DI AND ADX > 25"
    cci:
      enabled: true
      score: 1.0
      timeframes: [1m, 5m, 15m, 1h]
      condition: "CCI > 100"
    ichimoku:
      enabled: true
      score: 2.0
      timeframes: [15m, 1h, 4h]
      condition: "price > cloud_top AND tenkan > kijun"
    atr:
      enabled: true
      score: 0.8
      timeframes: [1m, 5m, 15m]
      condition: "ATR > SMA(ATR, 14) AND ATR rising"
    tema:
      enabled: true
      score: 1.2
      timeframes: [1m, 5m, 15m]
      condition: "TEMA9 > TEMA21"
    obv:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h]
      condition: "OBV increasing"
    choppiness:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h]
      condition: "choppiness < 38.2"
    mfi:
      enabled: true
      score: 1.3
      timeframes: [1m, 15m, 1h]
      condition: "MFI < 20"
    donchian:
      enabled: true
      score: 1.4
      timeframes: [5m, 15m, 1h]
      condition: "price breakout upper_band"
    rvi:
      enabled: false
      is_implemented: false
      score: 1.1
      timeframes: [15m, 1h]
      condition: "RVI > Signal"
    ultimate_oscillator:
      enabled: false
      is_implemented: false
      score: 1.2
      timeframes: [5m, 15m, 1h]
      condition: "UO < 30"
    fisher_transform:
      enabled: false
      is_implemented: false
      score: 1.2
      timeframes: [5m, 15m]
      condition: "Fisher crosses above Signal"
    stc:
      enabled: false
      is_implemented: false
      score: 1.3
      timeframes: [15m, 1h]
      condition: "STC > 25"
    connors_rsi:
      enabled: false
      is_implemented: false
      score: 1.3
      timeframes: [5m, 15m]
      condition: "ConnorsRSI < 20"
    poc_volume_profile:
      enabled: false
      is_implemented: false
      score: 1.4
      timeframes: [1h, 4h]
      condition: "Rebond sur Point of Control"
    anchored_vwap:
      enabled: false
      is_implemented: false
      score: 1.4
      timeframes: [15m, 1h, 4h]
      condition: "Prix > AVWAP ancré au plus bas récent"
  short:
    rsi:
      enabled: true
      score: 1.5
      timeframes: [1m, 5m, 15m, 1h, 4h]
      periods: [6, 14]
      condition: "RSI < 22 (6) OR RSI < 30 (14)"
    ema:
      enabled: true
      score: 1.5
      timeframes: [1m, 5m, 15m, 1h, 4h]
      cross: "EMA9 < EMA21"
      price_vs_ema200: true
    macd:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h, 4h]
      condition: "MACD < Signal AND divergence négative"
    bollinger:
      enabled: true
      score: 1.0
      timeframes: [5m, 15m, 4h]
      condition: "Rejet bande supérieure"
    stochastic_rsi:
      enabled: true
      score: 1.2
      timeframes: [1m, 5m]
      condition: "StochRSI > 0.8 + croisement baissier"
    vwap:
      enabled: true
      score: 1.2
      timeframes: [1m, 5m, 15m]
      condition: "Prix < VWAP + volume vendeur"
    volume:
      enabled: true
      score: 1.3
      timeframes: [1m, 5m, 15m, 1h]
      condition: "Volume vendeur anormal sur cassure support"
    candle:
      enabled: true
      score: 1.0
      timeframes: [1m, 5m, 15m, 1h]
      pattern: "Rejet haut (bougie rouge avec mèche haute dominante)"
    supertrend:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h, 4h]
      condition: "Prix < Supertrend"
    adx:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h, 4h]
      condition: "+DI < -DI AND ADX > 25"
    cci:
      enabled: true
      score: 1.0
      timeframes: [1m, 5m, 15m, 1h]
      condition: "CCI < -100"
    ichimoku:
      enabled: true
      score: 2.0
      timeframes: [15m, 1h, 4h]
      condition: "price < cloud_bottom AND tenkan < kijun"
    atr:
      enabled: true
      score: 0.8
      timeframes: [1m, 5m, 15m]
      condition: "ATR > SMA(ATR, 14) AND ATR rising"
    tema:
      enabled: true
      score: 1.2
      timeframes: [1m, 5m, 15m]
      condition: "TEMA9 < TEMA21"
    obv:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h]
      condition: "OBV divergence with price"
    choppiness:
      enabled: true
      score: 1.0
      timeframes: [15m, 1h]
      condition: "choppiness > 61.8"
    mfi:
      enabled: true
      score: 1.3
      timeframes: [1m, 15m, 1h]
      condition: "MFI > 80"
    donchian:
      enabled: true
      score: 1.4
      timeframes: [5m, 15m, 1h]
      condition: "price breakout lower_band"
    rvi:
      enabled: false
      is_implemented: false
      score: 1.1
      timeframes: [15m, 1h]
      condition: "RVI < Signal"
    ultimate_oscillator:
      enabled: false
      is_implemented: false
      score: 1.2
      timeframes: [5m, 15m, 1h]
      condition: "UO > 70"
    fisher_transform:
      enabled: false
      is_implemented: false
      score: 1.2
      timeframes: [5m, 15m]
      condition: "Fisher crosses below Signal"
    stc:
      enabled: false
      is_implemented: false
      score: 1.3
      timeframes: [15m, 1h]
      condition: "STC < 75"
    connors_rsi:
      enabled: false
      is_implemented: false
      score: 1.3
      timeframes: [5m, 15m]
      condition: "ConnorsRSI > 80"
    poc_volume_profile:
      enabled: false
      is_implemented: false
      score: 1.4
      timeframes: [1h, 4h]
      condition: "Rejet depuis Point of Control"
    anchored_vwap:
      enabled: false
      is_implemented: false
      score: 1.4
      timeframes: [15m, 1h, 4h]
      condition: "Prix < AVWAP ancré au plus haut récent"
