services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      string $bitmartWsUri: '%env(BITMART_WS_URI)%'
      string $ctrlAddress: '%env(CTRL_ADDR)%'
      int $subscribeBatch: '%env(int:SUBSCRIBE_BATCH)%'
      int $subscribeDelayMs: '%env(int:SUBSCRIBE_DELAY_MS)%'
      int $pingIntervalS: '%env(int:PING_INTERVAL_S)%'

  App\Command\WsWorkerCommand:
    public: true

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Tests}'
