# technical_indicator/indicator_rules.yaml
timeframes:
  4h:
    threshold: 0.8
    conditions:
      - indicator: rsi
        params: { period: 14 }
        op: "<"
        value: 30
        weight: 0.5
        side: "LONG"
        reason: "RSI < 30"
      - indicator: macd
        params: { fast: 12, slow: 26, signal: 9 }
        op: ">"
        value: 0
        weight: 0.5
        side: "LONG"
        reason: "MACD > 0"

  1m:
    threshold: 0.7
    conditions:
      - indicator: ema
        params: { period: 20 }
        op: ">"
        value: 0           # comparé à close/ema -> adapter si tu veux un ratio
        weight: 0.4
        side: "LONG"
        reason: "Close above EMA20"
      - indicator: supertrend
        params: { period: 10, multiplier: 3 }
        op: "=="
        value: 1           # direction=1 => tendance haussière (à adapter selon ton implémentation)
        weight: 0.6
        side: "LONG"
        reason: "Supertrend up"
