strategies:
  long:
    name: scalping_long_levier_max
    timeframe: 1m
    levier: 100
    position_size_pct: 1
    conditions:
      - indicateur: VWAP
        condition: prix > VWAP
      - indicateur: Supertrend
        condition: Supertrend = bullish
      - indicateur: EMA
        condition: EMA_21 > EMA_200
      - indicateur: Volume
        condition: volume > moyenne_volume_20
      - indicateur: RSI
        condition: RSI_14 >= 35 and RSI_14 <= 50
      - indicateur: Candle
        condition: pattern in ["bullish_engulfing", "marubozu_haussier"]
      - indicateur: ATR
        condition: ATR_14 < 0.35
    invalidation:
      - condition: prix < VWAP
      - condition: RSI > 70
      - condition: Supertrend = bearish
      - condition: volume < moyenne_volume_20
    risk_management:
      stop_loss_pct: 0.3
      take_profit_pct: 1.2
      trailing_stop: true
      breakeven: true

  short:
    name: scalping_short_levier_max
    timeframe: 1m
    levier: 100
    position_size_pct: 1
    conditions:
      - indicateur: VWAP
        condition: prix < VWAP
      - indicateur: Supertrend
        condition: Supertrend = bearish
      - indicateur: EMA
        condition: EMA_21 < EMA_200
      - indicateur: Volume
        condition: volume > moyenne_volume_20
      - indicateur: RSI
        condition: RSI_14 >= 50 and RSI_14 <= 65
      - indicateur: Candle
        condition: pattern in ["bearish_engulfing", "marubozu_baissier"]
      - indicateur: ATR
        condition: ATR_14 < 0.35
    invalidation:
      - condition: prix > VWAP
      - condition: RSI < 30
      - condition: Supertrend = bullish
      - condition: volume < moyenne_volume_20
    risk_management:
      stop_loss_pct: 0.3
      take_profit_pct: 1.2
      trailing_stop: true
      breakeven: true