<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251012195623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blacklisted_contract ADD reason VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE blacklisted_contract ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL');
        $this->addSql('UPDATE blacklisted_contract SET created_at = NOW() WHERE created_at IS NULL');
        $this->addSql('ALTER TABLE blacklisted_contract ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE blacklisted_contract ADD expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE blacklisted_contract ALTER id DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN blacklisted_contract.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN blacklisted_contract.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX idx_contracts_quote_currency');
        $this->addSql('DROP INDEX idx_contracts_status');
        $this->addSql('DROP INDEX idx_contracts_volume_24h');
        $this->addSql('ALTER TABLE contracts ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE contracts ALTER symbol TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE contracts ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE contracts ALTER base_currency TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE contracts ALTER quote_currency TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE contracts ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE contracts ALTER inserted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE contracts ALTER inserted_at DROP DEFAULT');
        $this->addSql('ALTER TABLE contracts ALTER inserted_at SET NOT NULL');
        $this->addSql('ALTER TABLE contracts ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE contracts ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE contracts ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN contracts.inserted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN contracts.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER symbol TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER timeframe TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER kline_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER inserted_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER inserted_at SET NOT NULL');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN indicator_snapshots.kline_time IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN indicator_snapshots.inserted_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN indicator_snapshots.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('ALTER TABLE klines ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE klines ALTER symbol TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE klines ALTER timeframe TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE klines ALTER open_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE klines ALTER source TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE klines ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE klines ALTER inserted_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE klines ALTER inserted_at SET NOT NULL');
        $this->addSql('ALTER TABLE klines ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE klines ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE klines ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN klines.open_time IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN klines.inserted_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN klines.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('ALTER TABLE mtf_audit ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mtf_audit ALTER symbol TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE mtf_audit ALTER step TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE mtf_audit ALTER timeframe TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE mtf_audit ALTER details SET NOT NULL');
        $this->addSql('ALTER TABLE mtf_audit ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_audit ALTER created_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE mtf_audit ALTER created_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN mtf_audit.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('DROP INDEX idx_mtf_lock_expires_at');
        $this->addSql('DROP INDEX idx_mtf_lock_process_id');
        $this->addSql('ALTER TABLE mtf_lock ALTER acquired_at TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_lock ALTER acquired_at DROP DEFAULT');
        $this->addSql('ALTER TABLE mtf_lock ALTER expires_at TYPE TIMESTAMPTZ');
        $this->addSql('DROP INDEX idx_mtf_state_symbol');
        $this->addSql('ALTER TABLE mtf_state ADD k5m_time TIMESTAMPTZ DEFAULT NULL');
        $this->addSql('ALTER TABLE mtf_state ADD k1m_time TIMESTAMPTZ DEFAULT NULL');
        $this->addSql('ALTER TABLE mtf_state ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mtf_state ALTER k4h_time TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_state ALTER k1h_time TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_state ALTER k15m_time TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_state ALTER updated_at TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_state ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER INDEX mtf_state_symbol_key RENAME TO ux_mtf_state_symbol');
        $this->addSql('DROP INDEX idx_mtf_switch_key');
        $this->addSql('ALTER TABLE mtf_switch ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mtf_switch ALTER created_at TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_switch ALTER created_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE mtf_switch ALTER updated_at TYPE TIMESTAMPTZ');
        $this->addSql('ALTER TABLE mtf_switch ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER INDEX mtf_switch_switch_key_key RENAME TO ux_mtf_switch_key');
        $this->addSql('ALTER TABLE order_plan ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_plan ALTER symbol TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE order_plan ALTER plan_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE order_plan ALTER plan_time SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE order_plan ALTER plan_time SET NOT NULL');
        $this->addSql('ALTER TABLE order_plan ALTER side TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE order_plan ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE order_plan ALTER status SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN order_plan.plan_time IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('ALTER TABLE signals ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE signals ALTER symbol TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE signals ALTER timeframe TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE signals ALTER kline_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE signals ALTER side TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE signals ALTER meta SET NOT NULL');
        $this->addSql('ALTER TABLE signals ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE signals ALTER inserted_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE signals ALTER inserted_at SET NOT NULL');
        $this->addSql('ALTER TABLE signals ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE signals ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE signals ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN signals.kline_time IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN signals.inserted_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN signals.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('ALTER TABLE validation_cache ALTER cache_key TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE validation_cache ALTER expires_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE validation_cache ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE validation_cache ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE validation_cache ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN validation_cache.expires_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN validation_cache.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mtf_state DROP k5m_time');
        $this->addSql('ALTER TABLE mtf_state DROP k1m_time');
        $this->addSql('CREATE SEQUENCE mtf_state_id_seq');
        $this->addSql('SELECT setval(\'mtf_state_id_seq\', (SELECT MAX(id) FROM mtf_state))');
        $this->addSql('ALTER TABLE mtf_state ALTER id SET DEFAULT nextval(\'mtf_state_id_seq\')');
        $this->addSql('ALTER TABLE mtf_state ALTER k4h_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_state ALTER k1h_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_state ALTER k15m_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_state ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_state ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_mtf_state_symbol ON mtf_state (symbol)');
        $this->addSql('ALTER INDEX ux_mtf_state_symbol RENAME TO mtf_state_symbol_key');
        $this->addSql('ALTER TABLE blacklisted_contract DROP reason');
        $this->addSql('ALTER TABLE blacklisted_contract DROP created_at');
        $this->addSql('ALTER TABLE blacklisted_contract DROP expires_at');
        $this->addSql('CREATE SEQUENCE blacklisted_contract_id_seq');
        $this->addSql('SELECT setval(\'blacklisted_contract_id_seq\', (SELECT MAX(id) FROM blacklisted_contract))');
        $this->addSql('ALTER TABLE blacklisted_contract ALTER id SET DEFAULT nextval(\'blacklisted_contract_id_seq\')');
        $this->addSql('CREATE SEQUENCE mtf_switch_id_seq');
        $this->addSql('SELECT setval(\'mtf_switch_id_seq\', (SELECT MAX(id) FROM mtf_switch))');
        $this->addSql('ALTER TABLE mtf_switch ALTER id SET DEFAULT nextval(\'mtf_switch_id_seq\')');
        $this->addSql('ALTER TABLE mtf_switch ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_switch ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE mtf_switch ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_switch ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_mtf_switch_key ON mtf_switch (switch_key)');
        $this->addSql('ALTER INDEX ux_mtf_switch_key RENAME TO mtf_switch_switch_key_key');
        $this->addSql('CREATE SEQUENCE indicator_snapshots_id_seq');
        $this->addSql('SELECT setval(\'indicator_snapshots_id_seq\', (SELECT MAX(id) FROM indicator_snapshots))');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER id SET DEFAULT nextval(\'indicator_snapshots_id_seq\')');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER timeframe TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER kline_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER inserted_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER inserted_at DROP NOT NULL');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE indicator_snapshots ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN indicator_snapshots.kline_time IS NULL');
        $this->addSql('COMMENT ON COLUMN indicator_snapshots.inserted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN indicator_snapshots.updated_at IS NULL');
        $this->addSql('CREATE SEQUENCE mtf_audit_id_seq');
        $this->addSql('SELECT setval(\'mtf_audit_id_seq\', (SELECT MAX(id) FROM mtf_audit))');
        $this->addSql('ALTER TABLE mtf_audit ALTER id SET DEFAULT nextval(\'mtf_audit_id_seq\')');
        $this->addSql('ALTER TABLE mtf_audit ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE mtf_audit ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE mtf_audit ALTER step TYPE TEXT');
        $this->addSql('ALTER TABLE mtf_audit ALTER step TYPE TEXT');
        $this->addSql('ALTER TABLE mtf_audit ALTER timeframe TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE mtf_audit ALTER details DROP NOT NULL');
        $this->addSql('ALTER TABLE mtf_audit ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_audit ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE mtf_audit ALTER created_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN mtf_audit.created_at IS NULL');
        $this->addSql('CREATE SEQUENCE klines_id_seq');
        $this->addSql('SELECT setval(\'klines_id_seq\', (SELECT MAX(id) FROM klines))');
        $this->addSql('ALTER TABLE klines ALTER id SET DEFAULT nextval(\'klines_id_seq\')');
        $this->addSql('ALTER TABLE klines ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE klines ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE klines ALTER timeframe TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE klines ALTER open_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE klines ALTER source TYPE TEXT');
        $this->addSql('ALTER TABLE klines ALTER source TYPE TEXT');
        $this->addSql('ALTER TABLE klines ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE klines ALTER inserted_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE klines ALTER inserted_at DROP NOT NULL');
        $this->addSql('ALTER TABLE klines ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE klines ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE klines ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN klines.open_time IS NULL');
        $this->addSql('COMMENT ON COLUMN klines.inserted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN klines.updated_at IS NULL');
        $this->addSql('ALTER TABLE mtf_lock ALTER acquired_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE mtf_lock ALTER acquired_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE mtf_lock ALTER expires_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('CREATE INDEX idx_mtf_lock_expires_at ON mtf_lock (expires_at)');
        $this->addSql('CREATE INDEX idx_mtf_lock_process_id ON mtf_lock (process_id)');
        $this->addSql('CREATE SEQUENCE contracts_id_seq');
        $this->addSql('SELECT setval(\'contracts_id_seq\', (SELECT MAX(id) FROM contracts))');
        $this->addSql('ALTER TABLE contracts ALTER id SET DEFAULT nextval(\'contracts_id_seq\')');
        $this->addSql('ALTER TABLE contracts ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER name TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER name TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER base_currency TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER base_currency TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER quote_currency TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER quote_currency TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER status TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER status TYPE TEXT');
        $this->addSql('ALTER TABLE contracts ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE contracts ALTER inserted_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE contracts ALTER inserted_at DROP NOT NULL');
        $this->addSql('ALTER TABLE contracts ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE contracts ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE contracts ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN contracts.inserted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN contracts.updated_at IS NULL');
        $this->addSql('CREATE INDEX idx_contracts_quote_currency ON contracts (quote_currency)');
        $this->addSql('CREATE INDEX idx_contracts_status ON contracts (status)');
        $this->addSql('CREATE INDEX idx_contracts_volume_24h ON contracts (volume_24h)');
        $this->addSql('CREATE SEQUENCE order_plan_id_seq');
        $this->addSql('SELECT setval(\'order_plan_id_seq\', (SELECT MAX(id) FROM order_plan))');
        $this->addSql('ALTER TABLE order_plan ALTER id SET DEFAULT nextval(\'order_plan_id_seq\')');
        $this->addSql('ALTER TABLE order_plan ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE order_plan ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE order_plan ALTER plan_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE order_plan ALTER plan_time SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE order_plan ALTER plan_time DROP NOT NULL');
        $this->addSql('ALTER TABLE order_plan ALTER side TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE order_plan ALTER status TYPE TEXT');
        $this->addSql('ALTER TABLE order_plan ALTER status DROP NOT NULL');
        $this->addSql('ALTER TABLE order_plan ALTER status TYPE TEXT');
        $this->addSql('COMMENT ON COLUMN order_plan.plan_time IS NULL');
        $this->addSql('ALTER TABLE validation_cache ALTER cache_key TYPE TEXT');
        $this->addSql('ALTER TABLE validation_cache ALTER expires_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE validation_cache ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE validation_cache ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE validation_cache ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN validation_cache.expires_at IS NULL');
        $this->addSql('COMMENT ON COLUMN validation_cache.updated_at IS NULL');
        $this->addSql('CREATE SEQUENCE signals_id_seq');
        $this->addSql('SELECT setval(\'signals_id_seq\', (SELECT MAX(id) FROM signals))');
        $this->addSql('ALTER TABLE signals ALTER id SET DEFAULT nextval(\'signals_id_seq\')');
        $this->addSql('ALTER TABLE signals ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE signals ALTER symbol TYPE TEXT');
        $this->addSql('ALTER TABLE signals ALTER timeframe TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE signals ALTER kline_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE signals ALTER side TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE signals ALTER meta DROP NOT NULL');
        $this->addSql('ALTER TABLE signals ALTER inserted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE signals ALTER inserted_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE signals ALTER inserted_at DROP NOT NULL');
        $this->addSql('ALTER TABLE signals ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE signals ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE signals ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN signals.kline_time IS NULL');
        $this->addSql('COMMENT ON COLUMN signals.inserted_at IS NULL');
        $this->addSql('COMMENT ON COLUMN signals.updated_at IS NULL');
    }
}
