services:
  # =====================
  # --- Logging Services ---
  # =====================
  
  App\Logging\CustomLineFormatter:
    public: true
    tags:
      - { name: monolog.formatter, alias: custom_line }
  
  # =====================
  # --- Logger Helpers ---
  # =====================
  
  App\Logging\LoggerHelper:
    arguments:
      $logger: '@monolog.logger'
    public: true
  
  # =====================
  # --- Channel Loggers ---
  # =====================
  
  # Logger pour le canal validation
  monolog.logger.validation:
    parent: monolog.logger
    arguments: ['validation']
    tags:
      - { name: monolog.logger, channel: validation }
  
  # Logger pour le canal signals
  monolog.logger.signals:
    parent: monolog.logger
    arguments: ['signals']
    tags:
      - { name: monolog.logger, channel: signals }
  
  # Logger pour le canal positions
  monolog.logger.positions:
    parent: monolog.logger
    arguments: ['positions']
    tags:
      - { name: monolog.logger, channel: positions }
  
  # Logger pour le canal indicators
  monolog.logger.indicators:
    parent: monolog.logger
    arguments: ['indicators']
    tags:
      - { name: monolog.logger, channel: indicators }
  
  # Logger pour le canal highconviction
  monolog.logger.highconviction:
    parent: monolog.logger
    arguments: ['highconviction']
    tags:
      - { name: monolog.logger, channel: highconviction }
  
  # Logger pour le canal pipeline_exec
  monolog.logger.pipeline_exec:
    parent: monolog.logger
    arguments: ['pipeline_exec']
    tags:
      - { name: monolog.logger, channel: pipeline_exec }
  
  # Logger pour le canal deprecation
  monolog.logger.deprecation:
    parent: monolog.logger
    arguments: ['deprecation']
    tags:
      - { name: monolog.logger, channel: deprecation }
  
  # Logger pour le canal global-severity
  monolog.logger.global_severity:
    parent: monolog.logger
    arguments: ['global-severity']
    tags:
      - { name: monolog.logger, channel: global-severity }
