#bitmart_kline:
#    path: /api/bitmart/kline
#    controller: App\Controller\Bitmart\KlineController
#    methods: [POST]

bitmart_contracts:
    path: /api/bitmart/contracts
    controller: App\Controller\Bitmart\ContractsController
    methods: [GET]
